### PR TITLE
WIP : Add fixes for 12/17/19

### LINKED ISSUE #837: Fix Capistrano Deploy Issues for QA
These are for the fixes for the QA deploy on 12/17/19

### PR DESCRIPTION
**Pull request by bsp3ars**
Fixes #837

Fixes the QA uploads folder symlink, and also fixes the restart_sidekiq script

### CODE REVIEW

File: script/start_prod.sh [hunk 1]
```diff
@@ -16,7 +16,7 @@ rm /srv/apps/scholar_capistrano/shared/public/uploads 2> /dev/null
 rm /srv/apps/scholar_capistrano/shared/public/branding 2> /dev/null
 mkdir -p "$(dirname "$(dirname "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" )" )/shared/public/system" 2> /dev/null
 ln -s /mnt/common/avatars "$(dirname "$(dirname "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" )" )/shared/public/system/avatars" 2> /dev/null
```
Comment (hortongn) [inline script/start_prod.sh]: @bsp3ars I noticed that this line uses `/shared/public/system/avatars` while the start_qa.sh script uses `/shared/public/system`.    Let's resolve that so both the qa and prod scripts are the same.

File: script/start_prod.sh [hunk 2]
```diff
@@ -16,7 +16,7 @@ rm /srv/apps/scholar_capistrano/shared/public/uploads 2> /dev/null
...
-ln -s /mnt/common/scholar-public-uploads "$(dirname "$(dirname "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" )" )/shared/public/uploads/" 2> /dev/null
+ln -s /mnt/common/scholar-public-uploads "$(dirname "$(dirname "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" )" )/shared/public/uploads" 2> /dev/null
 ln -s /mnt/common/branding "$(dirname "$(dirname "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" )" )/shared/public/branding" 2> /dev/null
```
Comment (hortongn) [inline script/start_prod.sh]: @bsp3ars I noticed that this line uses `/shared/public/branding` while the start_qa.sh script uses `/shared/public`.    Let's resolve that so both the qa and prod scripts are the same.
