### PR TITLE
Mock collection_type in catalog search spec

### LINKED ISSUE #298: Failing feature spec - missing collection type
### Descriptive summary

Failing test in `spec/features/catalog_search_spec.rb`

### Actual behavior
```
1) catalog searching with works and collections performing a search
     Failure/Error: visit '/catalog'
     
     ActionView::Template::Error:
       Couldn't find Hyrax::CollectionType matching GID 'gid://ucrate-hyrax2/hyrax-collectiontype/1'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/bundler/gems/hyrax-cea87d99966c/app/models/hyrax/collection_type.rb:52:in `find_by_gid!'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/bundler/gems/hyrax-cea87d99966c/app/presenters/hyrax/collection_presenter.rb:32:in `collection_type'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/bundler/gems/hyrax-cea87d99966c/app/presenters/hyrax/collection_presenter.rb:84:in `collection_type_badge'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/bundler/gems/hyrax-cea87d99966c/app/views/catalog/_index_header_list_collection.html.erb:3:in `__home_vagrant__rvm_gems_ruby_______bundler
_gems_hyrax_cea__d_____c_app_views_catalog__index_header_list_collection_html_erb__795105119925146387_131057400'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/blacklight-6.15.0/app/helpers/blacklight/render_partials_helper.rb:52:in `render_document_partial'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/blacklight-6.15.0/app/helpers/blacklight/render_partials_helper.rb:28:in `block in render_document_partials'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/blacklight-6.15.0/app/helpers/blacklight/render_partials_helper.rb:27:in `map'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/blacklight-6.15.0/app/helpers/blacklight/render_partials_helper.rb:27:in `render_document_partials'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/bundler/gems/hyrax-cea87d99966c/app/views/catalog/_document.html.erb:3:in `__home_vagrant__rvm_gems_ruby_______bundler_gems_hyrax_cea__d__
___c_app_views_catalog__document_html_erb__2746885949922130802_131101380'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/bundler/gems/hyrax-cea87d99966c/app/views/hyrax/collections/_collection.html.erb:2:in `__home_vagrant__rvm_gems_ruby_______bundler_gems_hy
rax_cea__d_____c_app_views_hyrax_collections__collection_html_erb__1165811476437223358_131126200'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/bundler/gems/hyrax-cea87d99966c/app/views/catalog/_document_list.html.erb:4:in `__home_vagrant__rvm_gems_ruby_______bundler_gems_hyrax_cea
__d_____c_app_views_catalog__document_list_html_erb__3427715391103625027_131158620'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/blacklight-6.15.0/app/helpers/blacklight/render_partials_helper.rb:77:in `render_document_index_with_view'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/blacklight-6.15.0/app/helpers/blacklight/render_partials_helper.rb:11:in `render_document_index'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/blacklight-6.15.0/app/views/catalog/_search_results.html.erb:21:in `__home_vagrant__rvm_gems_ruby_______gems_blacklight________app_vi
ews_catalog__search_results_html_erb___2973770733519429683_131977380'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/bundler/gems/hyrax-cea87d99966c/app/views/catalog/index.html.erb:6:in `__home_vagrant__rvm_gems_ruby_______bundler_gems_hyrax_cea__d_____c
_app_views_catalog_index_html_erb__3216949976333350955_132509600'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:190:in `call!'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:168:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:190:in `call!'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:168:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/etag.rb:25:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/conditional_get.rb:25:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:232:in `context'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:226:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/active-fedora-11.5.2/lib/active_fedora/ldp_cache.rb:26:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/flipflop-2.4.0/lib/flipflop/feature_cache.rb:12:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/railties-5.1.4/lib/rails/rack/logger.rb:36:in `call_app'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/railties-5.1.4/lib/rails/rack/logger.rb:24:in `block in call'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/railties-5.1.4/lib/rails/rack/logger.rb:24:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/runtime.rb:22:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/sendfile.rb:111:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/railties-5.1.4/lib/rails/engine.rb:522:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/urlmap.rb:68:in `block in call'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/urlmap.rb:53:in `each'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/urlmap.rb:53:in `call'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/rack-test-1.0.0/lib/rack/mock_session.rb:29:in `request'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/rack-test-1.0.0/lib/rack/test.rb:259:in `process_request'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/rack-test-1.0.0/lib/rack/test.rb:129:in `custom_request'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/rack-test-1.0.0/lib/rack/test.rb:58:in `get'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/capybara-2.17.0/lib/capybara/rack_test/browser.rb:69:in `process'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/capybara-2.17.0/lib/capybara/rack_test/browser.rb:41:in `process_and_follow_redirects'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/capybara-2.17.0/lib/capybara/rack_test/browser.rb:22:in `visit'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/capybara-2.17.0/lib/capybara/rack_test/driver.rb:44:in `visit'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/capybara-2.17.0/lib/capybara/session.rb:274:in `visit'
     # /home/vagrant/.rvm/gems/ruby-2.5.1/gems/capybara-2.17.0/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
     # ./spec/features/catalog_search_spec.rb:11:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # ActiveRecord::RecordNotFound:
     #   Couldn't find Hyrax::CollectionType matching GID 'gid://ucrate-hyrax2/hyrax-collectiontype/1'
     #   /home/vagrant/.rvm/gems/ruby-2.5.1/bundler/gems/hyrax-cea87d99966c/app/models/hyrax/collection_type.rb:52:in `find_by_gid!'
```
### Steps to reproduce the behavior

*bisect output*
```
rspec ./spec/controllers/callbacks_controller_spec.rb[1:2:2:1:1,1:2:4:1:1,1:2:6:1:1] ./spec/controllers/collection_exports_controller_spec.rb[1:2:1:2:1,1:2:1:4:1,1:2:2:3:1] ./spec/controllers/hyrax/student_works_controller_spec.rb[1:1] ./spec/features/batch_edit_spec.rb[1:1:2] ./spec/features/catalog_search_spec.rb[1:1:1] ./spec/features/collection_export_spec.rb[1:2:3:1] ./spec/features/collection_spec.rb[1:1:4:1] ./spec/features/collection_type_spec.rb[1:2:1,1:3:1:3:1] ./spec/features/create_child_work_spec.rb[1:1,1:2:1,1:2:2] ./spec/features/dashboard/collection_spec.rb[1:4:1:2,1:4:2:1,1:4:3:1,1:6:1:1:2,1:7:3:1,1:7:4:1,1:9:1:1,1:9:1:2,1:9:1:3,1:9:2:1] ./spec/features/edit_file_spec.rb[1:1:1] ./spec/features/ownership_transfer_spec.rb[1:1:1:1,1:2:1] ./spec/features/uc_shibboleth_spec.rb[1:3:1] ./spec/features/work_share_spec.rb[1:1] ./spec/forms/hyrax/document_form_spec.rb[1:1] ./spec/presenters/hyrax/dataset_presenter_spec.rb[1:1] ./spec/services/work_metadata_attribute_mapper_spec.rb[1:2:2] ./spec/views/_user_util_links.html.erb_spec.rb[1:1] --seed 1234
```

### PR DESCRIPTION
**Pull request by crowesn**
Fixes #298 

Catalog search spec was failing with error missing collection type. Added mock to spec with required collection type.

``` ruby
let!(:collection_type) { create(:collection_type, id: 1) }
```

Changes proposed in this pull request:
* tweak to `spec/features/catalog_search_spec.rb`

### CODE REVIEW

File: spec/features/catalog_search_spec.rb [hunk 1]
```diff
@@ -4,6 +4,7 @@
 
 RSpec.describe 'catalog searching', type: :feature do
   let(:user) { create(:user) }
+  let!(:collection_type) { create(:collection_type, id: 1) }
```
Comment (hortongn) [inline spec/features/catalog_search_spec.rb]: I think you will also need to adjust the `:collection` let statement down on line 24 to use this collection_type.  Something like 

`let!(:collection) { create(:public_collection, collection_type_gid: collection_type.gid, keyword: ['collection_keyword', 'shared_keyword']) }`

When I ran this individual spec the first time it passed, but it then failed every time after that because it was expecting a collection_type with ID 2.  So associating the collection with the mocked collection type seems to fix that.

Travis doesn't hit this problem because it only runs the test once in a fresh environment.  But it fails locally when a collection type already pre-exists.

Comment (crowesn) [reply spec/features/catalog_search_spec.rb]: @hortongn Done!
